# SignageOS Display 2 — HDMI-A-2
[core]
backend=drm-backend.so
shell=kiosk-shell.so
idle-time=0
repaint-window=8

[output]
name=HDMI-A-1
enabled=false

[output]
name=HDMI-A-2
mode=1920x1080@60
transform=normal

[keyboard]
keymap_rules=evdev
keymap_layout=gb
